### ISSUE TITLE
Sometimes doesnt stol anything

### ISSUE THREAD

**Issue by MohammedGeorge** [uanc/NiceRAT#68]
Hey im using file dropper maybe because of this dont steal anyshit ? it will install temp or appdata and execute

**Comment by MohammedGeorge** [comment]
![image](https://github.com/uanc/NiceRAT/assets/160282892/cb009fb4-e1c0-4681-b9dc-6f10424288ef)

**Comment by MohammedGeorge** [comment]
![image](https://github.com/uanc/NiceRAT/assets/160282892/8c47119c-e91d-418a-9cea-b45238d5d2e3)
Like this

**Comment by MohammedGeorge** [comment]
250 password but 0 cookie idk

**Comment by uanc** [comment]
Might be issue with upload form some countries, you can inolement ur own uplaod file logic.
